### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by mattfox** [oremanj/python-netfilterqueue#13]
Done when there are some tests:
- For key methods
- Double unbind()- see https://github.com/kti/python-netfilterqueue/pull/7
- Async use- see https://github.com/kti/python-netfilterqueue/pull/10
- Use Python socket- see https://github.com/kti/python-netfilterqueue/issues/5

**Comment by oremanj** [comment]
Closing this since we now have a reasonable testsuite! I don't know a good coverage tool for Cython modules, but the only thing obviously uncovered right now is `run_socket()`.
