### ISSUE TITLE
Cannot bind multiple queues 

### ISSUE THREAD

**Issue by fripSide** [oremanj/python-netfilterqueue#28]
When I try to use netfilter to bind two queue with different queue num, and I add two callbacks methods to bind with the two number.
nfqueue.bind(1, self.in_modify)
nfqueue.bind(2, self.out_modify)

However, the two queues are all bind to the second callback method.
https://github.com/kti/python-netfilterqueue/blob/master/netfilterqueue.pyx#L178

In this line, it's obvious that the pointer user_callback are overwrite when bind another queue. I think here should use a map to support different callbacks for each queue num.

**Comment by strictlymike** [comment]
It doesn't look like the `NetfilterQueue` class is intended to `bind()` to more than one queue at a time. I am working on a project that requires multiple callbacks and I made it work by creating an instance of the `NetfilterQueue` class for each queue I wanted to bind to.

**Comment by Kkevsterrr** [comment]
Can confirm running into the same problem as @fripSide. Running multiple queues works (per @strictlymike's suggestion), but note that the nfqueue.run() call is blocking (and I don't see a way in the API to signal an exit), so each queue would need to run out of its own thread/process and be killed on exit. Not the cleanest solution unfortunately, but works for now.

**Comment by jllorente** [comment]
Hi there!
I wrote this wrapper back in the day so I could better integrate it with `asyncio`, please check it out if you are interested!
https://github.com/jllorente/helpers_n_wrappers/blob/master/nfqueue3.py

**Comment by oremanj** [comment]
The bug where `bind()` of multiple queues will appear to succeed, and leak the queues, has been fixed; it now fails with a clear error. You can manage multiple queues by using multiple NetfilterQueue objects and the async support (wait for get_fd() to be readable, call run(False), rinse, repeat).
