### ISSUE TITLE
can not set payload correctly with length changed

### ISSUE THREAD

**Issue by rhoninzhang** [oremanj/python-netfilterqueue#29]
after changing the TCP payload, and the length is different, the program is abnormal:

iptables rule in test server:
```
iptables -A OUTPUT -p TCP -d [test client ip] -j NFQUEUE --queue-num 1
```

if the length is shorter after changed:
client can receive the modified payload, but the client send a RST connection to server while closing socket

if the length is longer:
client can receive the modified payload, but the server repeatedly to send the packet for several times, and the length looks like not changed via get_payload_len()

if the length is same, just replace content, all behave correctly

could you please help me? thanks, below is the test code:

```
from netfilterqueue import NetfilterQueue
from scapy.layers.inet import IP,TCP
from scapy.packet import Packet,Raw

def print_and_accept(pkt):
    msg = IP(pkt.get_payload())
    try:
        if msg.haslayer(TCP) and msg.haslayer(Raw):
            print msg[IP].show()
            print pkt.get_payload_len()
            _Data = 'for the hook test'
            msg[TCP].remove_payload()
            msg[TCP].add_payload(_Data)
            #msg[Raw].load = _Data
            #print msg[IP].show()
            msg[IP].len = len(msg)
            del msg[IP].chksum
            del msg[TCP].chksum
            msg = msg.__class__(str(msg))
            pkt.set_payload(str(msg))
            #new_msg = IP(pkt.get_payload())
            #print new_msg[TCP].payload
            #print new_msg[IP].show()
            print msg[IP].show()
            print pkt.get_payload_len()
            pkt.accept()
        else:
            pkt.accept()
    except Exception, err:
        print err
        pkt.accept()

nfqueue = NetfilterQueue()
nfqueue.bind(1, print_and_accept)
try:
    nfqueue.run()
except KeyboardInterrupt:
    print('')
```

**Comment by fripSide** [comment]
We can manually fix the length of raw packet,
pkt[IP].len = len(pkt)

**Comment by fripSide** [comment]
We can manually modify the length of packet,
pkt[IP].len = len(pkt)

**Comment by svolpe** [comment]
I tried the above example using netcat senting Hello.  I see the debug information showing its overwriting 'hello' with 'for the hook test' but the netcat at the other end still recieves 'hello'.  why is it not modifying the packet?

**Comment by Atiyeh-mohammadkhani** [comment]
Hello
what is code doing? >>>msg = msg.__class__(str(msg))

**Comment by Atiyeh-mohammadkhani** [comment]
Does this strategy work whit UDP packet? actually I test this for change udp packet size but for size above 1500 It send IP packet whit no source/destination IP address too!

**Comment by oremanj** [comment]
You can change the length of a UDP packet as long as you update the IP length, IP header checksum, UDP length, and UDP checksum fields. You cannot change the length of a TCP packet because it throws off the sequencing for later packets in the stream. (Well, maybe you can, but you will have to modify every packet after it... it's a huge chore and netfilterqueue doesn't give you any special tools for doing it.)
