### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bhojanidhrumil** [oremanj/python-netfilterqueue#51]
root@kali:~/PycharmProjects/arp_spoof# pip install NetfilterQueue
Collecting NetfilterQueue
  Using cached https://files.pythonhosted.org/packages/39/c4/8f73f70442aa4094b3c37876c96cddad2c3e74c058f6cd9cb017d37ffac0/NetfilterQueue-0.8.1.tar.gz
Building wheels for collected packages: NetfilterQueue
  Running setup.py bdist_wheel for NetfilterQueue ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wpnGkj/NetfilterQueue/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-2EQHXL --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'netfilterqueue' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ra3Yar/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c netfilterqueue.c -o build/temp.linux-x86_64-2.7/netfilterqueue.o
  netfilterqueue.c:439:10: fatal error: libnetfilter_queue/linux_nfnetlink_queue.h: No such file or directory
   #include "libnetfilter_queue/linux_nfnetlink_queue.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for NetfilterQueue
  Running setup.py clean for NetfilterQueue
Failed to build NetfilterQueue
Installing collected packages: NetfilterQueue
  Running setup.py install for NetfilterQueue ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wpnGkj/NetfilterQueue/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4vRz58/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'netfilterqueue' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ra3Yar/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c netfilterqueue.c -o build/temp.linux-x86_64-2.7/netfilterqueue.o
    netfilterqueue.c:439:10: fatal error: libnetfilter_queue/linux_nfnetlink_queue.h: No such file or directory
     #include "libnetfilter_queue/linux_nfnetlink_queue.h"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wpnGkj/NetfilterQueue/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4vRz58/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wpnGkj/NetfilterQueue/

``````````````````````````````````````I have already tried this`````````````````````````````````````````````````

root@kali:~/PycharmProjects/arp_spoof# apt-get install build-essential python-dev libnetfilter-queue-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.16-1).
The following packages were automatically installed and are no longer required:
  gdal-bin gdal-data libaec0 libarmadillo8 libarpack2 libavahi-gobject0 libcharls1 libdap25 libdapclient6v5 libdapserver7v5 libdee-1.0-4
  libepsilon1 libfcgi-bin libfcgi0ldbl libfolks-telepathy25 libfreexl1 libfyba0 libgail-3-0 libgcab-1.0-0 libgdal20 libgeotiff2
  libgfortran4 libgmime-3.0-0 libgtk2-perl libhdf4-0-alt libhdf5-100 libkmlbase1 libkmlconvenience1 libkmldom1 libkmlengine1
  libkmlregionator1 libkmlxsd1 liblwgeom-2.4-0 liblwgeom-dev libminizip1 libmission-control-plugins0 libnetcdf13 libogdi3.2 libpango-perl
  libpyside1.2 libqca2 libqca2-plugins libqgis-analysis2.18.21 libqgis-core2.18.21 libqgis-customwidgets libqgis-gui2.18.21
  libqgis-networkanalysis2.18.21 libqgis-server2.18.21 libqgispython2.18.21 libqhull7 libqtwebkit4 libqwt6abi1 libsane-extras
  libsane-extras-common libshiboken1.2v5 libspatialindex4v5 libspatialite7 libsuperlu5 libsz2 libtelepathy-glib0 liburiparser1
  libwhisker2-perl libxapian30 libxerces-c3.2 libzeitgeist-2.0-0 odbcinst odbcinst1debian2 python-backports.functools-lru-cache
  python-backports.ssl-match-hostname python-cycler python-gdal python-kiwisolver python-matplotlib python-owslib python-pam python-pyproj
  python-pyside.qtcore python-pyside.qtgui python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite python-qgis
  python-qgis-common python-qt4-sql python-shapely python-subprocess32 python3.6 python3.6-minimal qt4-designer ruby-faraday
  telepathy-mission-control-5 x11proto-dri2-dev x11proto-gl-dev zeitgeist-core
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  cpp cpp-9 g++ g++-9 gcc gcc-9 gcc-9-base libasan5 libatomic1 libcc1-0 libgcc-9-dev libgcc1 libgomp1 libitm1 liblsan0 libquadmath0
  libstdc++-9-dev libstdc++6 libtsan0 libubsan1
Suggested packages:
  cpp-doc gcc-9-locales g++-multilib g++-9-multilib gcc-9-doc libstdc++6-9-dbg gcc-multilib autoconf automake libtool bison gcc-doc
  gcc-9-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libquadmath0-dbg
  libstdc++-9-doc
/usr/lib/apt/methods/http: relocation error: /lib/x86_64-linux-gnu/libgnutls.so.30: symbol _idn2_punycode_decode version IDN2_0.0.0 not defined in file libidn2.so.0 with link time reference
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (127)
E: Method /usr/lib/apt/methods/http did not start correctly

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

root@kali:~/PycharmProjects/net_cut# sudo apt-get install libnfnetlink-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  pkg-config
The following NEW packages will be installed:
  libnfnetlink-dev pkg-config
0 upgraded, 2 newly installed, 0 to remove and 2065 not upgraded.
Need to get 71.7 kB of archives.
After this operation, 242 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 pkg-config amd64 0.29-6 [63.5 kB]
Get:2 http://ftp.harukasan.org/kali kali-rolling/main amd64 libnfnetlink-dev amd64 1.0.1-3+b1 [8,178 B]
Fetched 71.7 kB in 14s (5,206 B/s)          
/usr/share/apt-listchanges/apt_listchanges.py:540: FutureWarning: Possible nested set at position 25
  email_re = re.compile(r'([a-zA-Z0-9_\+\-\.]+)@(([[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)')
Selecting previously unselected package pkg-config.
(Reading database ... 344645 files and directories currently installed.)
Preparing to unpack .../pkg-config_0.29-6_amd64.deb ...
Unpacking pkg-config (0.29-6) ...
Selecting previously unselected package libnfnetlink-dev.
Preparing to unpack .../libnfnetlink-dev_1.0.1-3+b1_amd64.deb ...
Unpacking libnfnetlink-dev (1.0.1-3+b1) ...
Setting up pkg-config (0.29-6) ...
Processing triggers for man-db (2.8.3-2) ...
Setting up libnfnetlink-dev (1.0.1-3+b1) ...

Can anyone help me with this please

**Comment by jllorente** [comment]
Hello there! I have sometimes run into problems too when installing under Ubuntu or Debian.
I have this _recipe_ now:
```
# apt install build-essential libnetfilter-queue-dev 
# pip3 install --upgrade -U git+https://github.com/kti/python-netfilterqueue
```
