### ISSUE TITLE
NetfilterQueue import error

### ISSUE THREAD

**Issue by harkaran911** [oremanj/python-netfilterqueue#72]
When I try to import and run the program in python2, it says that NetfilterQueue object has no attribute called 'blind',
When I try to import and run the program in python3, it says that NetfilterQueue it says PyString_FromStringAndSize.

![Screenshot_2021-12-30_00-08-54](https://user-images.githubusercontent.com/86826375/147693509-991936cc-b7c7-49c4-86c4-3a56d6690d88.png)

**Please See This Above Picture for more understanding.**

Please Help me.

**Comment by oremanj** [comment]
`blind()` doesn't work because the method you're trying to call is named `bind()` with no L. I believe I've fixed the other issue; can you try again with current master?
