### ISSUE TITLE
Is there anyway to use multiple netfilterqueue Python program to bind to the same queue?

### ISSUE THREAD

**Issue by XingSc29** [oremanj/python-netfilterqueue#73]
I am working on a project which requires different attacks (DNS spoofing, Code injection, File replacer, etc...). So, I need to have multiple netfilterqueue Python programs to intercept the incoming packets in NFQUEUE. However, when more than one netfilterqueue instances access the same queue, the following error will be shown:
>queue.bind(int(self.queue_num), self.process_packet)
>File "netfilterqueue.pyx", line 182, in netfilterqueue.NetfilterQueue.bind
>OSError: Failed to create queue 0.

**Comment by oremanj** [comment]
No, this is a limitation at the kernel level -- you can only have one process bound to each queue number. You would need to have a single receiver using `NetfilterQueue` and then multiplex out the packets to your different programs after that point.
