### ISSUE TITLE
NetfilterQueue() create socket fd and never release

### ISSUE THREAD

**Issue by 1ncande5cence** [oremanj/python-netfilterqueue#84]
Hi!  Here is my code.
```
self.out_nfqueue = netfilterqueue.NetfilterQueue()
self.out_nfqueue.bind(self.out_queue_num,self.out_callback)
self.out_nfqueue_socket = socket.fromfd(self.out_nfqueue.get_fd(),socket.AF_UNIX,socket.SOCK_STREAM)
... 
# when I finish
self.out_nfqueue.unbind()
self.out_nfqueue_socket.close()
```
In line 1, Class NetfilterQueue will create a FileDescriptor in /proc/fd/ .  But when I finish these code. this socket will not be released and still in /proc/fd/ . However the FileDescriptor created in line 3 will be released in line 7 nicely.
I need to call the above code many times. I discovered that the FileDescriptor created in line 1 can not be released correctly, which lead to crashes of opening too many filedescriptors  ( filedescriptor out of range in select() ).

So how should I solve this problem? Thanks!

**Comment by DOWRIGHTTV** [comment]
in the class __cinit__ there is support for passing in a fd that it will try to reuse. 

so -> self.out_nfqueue = netfilterqueue.NetfilterQueue(sockfd=SOCK_FD)
