### ISSUE TITLE
NetfilterQueue for python2

### ISSUE THREAD

**Issue by sanrise21** [oremanj/python-netfilterqueue#96]
I am using netfilterqueue with python3 but part of my work is using python2. Netfilter is not working with python2 and not getting installed. can anyone help how to install it on raspberry pi for python2?

**Comment by oremanj** [comment]
Third paragraph of the README:

> The current version of NetfilterQueue requires Python 3.6 or later. The last version with support for Python 2.7 was 0.9.0.

Try `pip install NetfilterQueue==0.9.0`. I’m not able to provide Python 2 support beyond that. It was legacy software even years ago and very few packages support it anymore.

**Comment by sanrise21** [comment]
ok,will try with it. Thanks

**Comment by sanrise21** [comment]
I am getting this error when using netfilterqueue with python2- ImportError: No module named _impl
is it due to python3 is latest and netfilterqueue for python2 supports very few packages?

**Comment by oremanj** [comment]
That might be because you’re running Python from within the python-netfilterqueue checkout directory. Try running from any other directory. See #81.
